name: displaying message welcome
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1 this is welcome
        run: echo "Welcome to Github Runner"
        
      - name: step2 
        run: ls

      - name: step3
        run: pwd

      - name: step4
        run: date
